server:
  port: 8083

spring:
  application:
    name: BILLING-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/smarttelecom_billingdb
    username: root
    password: 9441
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

usage:
  service:
    url: http://localhost:8084/
